spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/practice_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
   database-platform: org.hibernate.dialect.PostgreSQL81Dialect
   generate-ddl: true
   show-sql: true
